packages:
  # all packages in direct subdirs of packages/
  # - "client/**"
  - "client/lib/api-client"
  - "client/lib/react-hooks"
  - "client/lib/react-unittest"
  # - "api-sdk/**"
  - "client/sdk/core"
  - "client/sdk/app-center-gateway"
  - "client/ui/next-ui"
  - "client/ui/mui/react-core-mui"
  - "client/ui/react-animates"
  - "client/ui/react-performance-utilities"
  - "client/ui/react-core"
  - "client/ui/react-mobx-state"
  - "client/ui/react-viewFrames"
  - "client/ui/react-lazyload"
  - "client/ui/react-charts"
  - "client/ui/react-flow"

  # business logic
  - "client/builtIn/react-novels"
  - "client/builtIn/react-ums"
  - "client/builtIn/react-auth"
  - "client/builtIn/react-recruiter"

  # all packages in subdirs of components/
  - "server/libs/*"
  - "server/domain/api-authentication"
  - "server/domain/api-appcenter-gateway"
  - "server/domain/api-novels"
  - "server/domain/api-recruiter"
  - "server/domain/api-ums"
  - "server/modules/**"
  - "server/nestjs/**"

  # all packages in subdirs of shared/
  - "shared/**"

  # all packages in direct subdirs of packages/
  - "apps/nextjs-with-nextui"
  # exclude packages that are inside test directories
  - "!**/test/**"
